### ISSUE TITLE
Debug adapter slow to attach, or failing to attach

### ISSUE THREAD

**Issue by ccecvb** [vscode-abl/vscode-abl#176]
The debug adapter is slow to connect, or does not connect at all,

* _progress session started from within vscode terminal
* session stops at ` Use port 44099 for the Debugger to connect to. (11725)`
* select attach to AVM
* => long wait 
  * counted +/- 20 seconds in a successful session
  * I wait up to a minute before ending the session.

* Debug console remains empty until the connection is made

I activated Debug adapter Debug and Debug adapted trace, but at first I could not find any log files. 
I'm not sure which value for $TMP is used. I defined TMP in the workspace file.
 
### Fixed logging 
I added the following to my .bashrc
```
TMP=$HOME/tmp
export TMP
```
Now I have a /home/.../tmp/vscode-debug-adapter.txt.

It seems like a large portion (19 seconds) of a successful start is taken by excluding sources
It only takes 2 seconds to add 12478 rcode files

I don't have logging for an unsuccessful session yet.

## Environment

* OpenEdge ABL  v1.9.27 (pre-release) 
* VsCode over ssh on linux
* OpenEdge 12.8
 

```
  "configurations": [
    {
      "name": "Attach to AVM",
      "type": "abl",
      "request": "attach",
      "hostname": "127.0.0.1",
      "mode": "legacy",
      "port": 44099,
      "pause": true,
      "localRoot": "${workspaceFolder}"
    },

```

**Comment by gquerret** [comment]
As the debug output may contain private information, could you push it to https://upload.rssw.eu ?

**Comment by ccecvb** [comment]
@gquerret I uploaded vscode_abl_issue_176_logs.7z
It contains 2 logs which should be similar
and a trimmed-ok.log where I removed a lot of similar entries to better see how much time each step takes.

**Comment by gquerret** [comment]
Visiting the source directories is not supposed to take a lot of time when starting the debug adapter, as it only creates a list of file names (using the include / exclude patterns).  Could you share your `include`and `exclude` patterns ?
Or could you remove the `include` / `exclude` patterns and start the debug adapter ? Remote session doesn't even have to be started, I'm only interested in seeing if those patterns change how long it takes to browse the source directories.

**Comment by gquerret** [comment]
> I'm not sure which value for $TMP is used. I defined TMP in the workspace file.

I thought that `TMP` was always set on Linux, but it doesn't seem to be the case.

**Comment by ccecvb** [comment]
I'm currently back in the situation where the debugger does not start at all. 
No log file available

**Comment by ccecvb** [comment]
I found the location of all logs, I can zip and upload thzm if you thinks it's usefull.

The only error that seems remotely relevant  is this.

## remoteexthost.log 
```
2024-08-24 09:24:36.623 [error] Error: write after end
        at _write (node:internal/streams/writable:481:11)
        at Writable.write (node:internal/streams/writable:502:10)
        at /home/domain/user/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.10.0-linux-x64/dist/extension.js:2:127992
        at new Promise (<anonymous>)
        at s.write (/home/domain/user/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.10.0-linux-x64/dist/extension.js:2:127910)
        at f.doWrite (/home/domain/user/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.10.0-linux-x64/dist/extension.js:2:117513)
        at /home/domain/user/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.10.0-linux-x64/dist/extension.js:2:117408
        at runNextTicks (node:internal/process/task_queues:60:5)
        at process.processImmediate (node:internal/timers:449:9)

```

I'll close all vscode processes, clear the log directory and start over.

**Comment by ccecvb** [comment]
Managed to debug again, not yet sure how I got it connecting again.

I emptied our excludes file and it made a huge difference.
I still have 9000+ excluded sources "*.w" but now it only takes 500 ms

[2024-08-24T12:24:19.272+0200] [DEBUG] eu.rssw.openedge.ls.builder.q - [develop] Excluded file: /home/cce/cvb/workspaces/develop/git/ccesmarttools/CceFramework/src/devtools/runwin.w
...
[2024-08-24T12:24:19.766+0200] [DEBUG] eu.rssw.openedge.ls.builder.q - [develop] Excluded file: /home/cce/cvb/workspaces/develop/git/lisafin/applfin/src/fincon/icafp-s.w

**Comment by ccecvb** [comment]
Our excludes file is a combination of a list of patterns and a list of individual files.
It contained  individuele files that were already excluded by a pattern.

I reduced the size of the excludes file from 2177 lines to 483 files.
The delay during debug start now takes +/- 5 seconds

```
[2024-08-24T13:06:51.577+0200] [DEBUG] eu.rssw.openedge.ls.builder.q - [develop] Excluded file: /home/domain/user/workspaces/develop/git/ccesmarttools/CceFramework/src/devtools/generator/CodeGenerator.cls

[2024-08-24T13:06:56.489+0200] [DEBUG] eu.rssw.openedge.ls.builder.q - [develop] Excluded file: /home/domain/user/workspaces/develop/git/lisafin/applfin/src/fincon/icafp-s.w

```

**Comment by gquerret** [comment]
Ok, so the implementation of the include / exclude pattern seems to be the problem. I'll check the code and try to find exactly where the problem is.

**Comment by gquerret** [comment]
Found a somewhat expensive operation executed way too many times during initialization  🤯

I'll push a new version to the pre-release stream.

**Comment by gquerret** [comment]
Version 1.11.0 (in the pre-release stream) contains changes that should improve the performance of include / exclude patterns.

**Comment by gquerret** [comment]
@cverbiest  Did you see any improvement ?

**Comment by ccecvb** [comment]
@gquerret Sorry I missed your comment about the updated version
I makes a huge difference

Before 3.235 seconds
```
[2024-08-27T09:28:02.721+0200] [INFO] eu.rssw.openedge.dap.p -  --> Argument 'ablsrc': '/home/domain/user/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.10.0-linux-x64/resources/abl-src' (java.lang.String)

[2024-08-27T09:28:04.344+0200] [DEBUG] eu.rssw.openedge.ls.builder.q - [develop] Excluded file: /home/domain/user/workspaces/develop/git/domainsmarttools/domainFramework/src/devtools/generator/CodeGenerator.cls
[2024-08-27T09:28:07.579+0200] [DEBUG] eu.rssw.openedge.ls.builder.q - [develop] Excluded file: /home/domain/user/workspaces/develop/git/lisafin/applfin/src/fincon/icafp-s.w

``` 


after 0.825 seconds
```
[2024-09-04T07:29:43.820+0200] [INFO] eu.rssw.openedge.dap.p -  --> Argument 'ablsrc': '/home/domain/user/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.11.0-linux-x64/resources/abl-src' (java.lang.String)
[2024-09-04T07:29:45.376+0200] [DEBUG] eu.rssw.openedge.ls.builder.q - [develop] Excluded file: /home/domain/user/workspaces/develop/git/domainsmarttools/domainFramework/src/devtools/generator/CodeGenerator.cls
[2024-09-04T07:29:46.201+0200] [DEBUG] eu.rssw.openedge.ls.builder.q - [develop] Excluded file: /home/domain/user/workspaces/develop/git/lisafin/applfin/src/fincon/icafp-s.w

```
