### ISSUE TITLE
New sonarlint plugin - installation error

### ISSUE THREAD

**Issue by kenherring-rkt** [vscode-abl/vscode-abl#181]
Still seeing if I can figure this out, but am running into this error when installing [sonarlint-vscode V4.8.99001](https://github.com/Riverside-Software/sonarlint-vscode/releases/tag/V4.8.99001).

Error from command line, though I get the same thing when using the UI to install.

```bash
$ code --install-extension target/sonarlint-abl-4.8.0.vsix 
Installing extensions...
Error: End of central directory record signature not found. Either not a zip file, or file is truncated.
    at c (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:18:2260)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:18:3710
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\yauzl\index.js:40:7
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\yauzl\index.js:190:5
    at Immediate.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\yauzl\index.js:705:38)
    at process.processImmediate (node:internal/timers:478:21) {
  code: 'Extract',
  name: 'Extract'
}
```

**Comment by kenherring-rkt** [comment]
My prior curl command to download the vsix was returning a size zero file.   Needed to add the `-L` flag.

```bash
## download the vsix
curl -L -o target/sonarlint-abl-4.8.0.vsix \
     https://github.com/Riverside-Software/sonarlint-vscode/releases/download/V4.8.99001/sonarlint-abl-4.8.0.vsix

## install the extension
code --install-extension target/sonarlint-abl-4.8.0.vsix
```
