### ISSUE TITLE
java.nio.file.FileAlreadyExistsException if build target is symbolic link

### ISSUE THREAD

**Issue by ccecvb** [vscode-abl/vscode-abl#187]
Related to #186 

I found why the language server failed to start in that case.

The build target was a symbolic link to a directory

After changing the target to a local directory that error went away.

```
[2024-09-06T13:59:32.539+0200] [INFO] Command line arguments: 
[2024-09-06T13:59:32.649+0200] [INFO] vscode.rootDir: /home/user/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.10.0/resources
[2024-09-06T13:59:32.987+0200] [INFO] LanguageServerInfo: 1.15.0-61e03c1 -- ClientInfo: Visual Studio Code 1.93.0 -- JVM: Eclipse Adoptium 17.0.12+7
[2024-09-06T13:59:32.987+0200] [INFO] Client Capabilities: WS Config true -- WS Folder true -- Diagnotics true -- Symbol Hierarchy true -- Document Highlight true
[2024-09-06T13:59:32.987+0200] [INFO] Semantic tokens support: true - Multiline tokens: false - Overlapping tokens: false
[2024-09-06T13:59:33.017+0200] [INFO] Looking for project JSON in workspace folder file:///appl/lisaccp
[2024-09-06T13:59:33.063+0200] [INFO] [lisaccp] Current profile: default
[2024-09-06T13:59:33.064+0200] [INFO] [lisaccp] Progress version : 11.7 -> /usr/oe117
[2024-09-06T13:59:33.085+0200] [ERROR] Unable to open project
java.nio.file.FileAlreadyExistsException: /appl/lisaccp/obnl
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectories(Unknown Source)
	at eu.rssw.openedge.ls.builder.s.a(SourceFile:1916)
	at eu.rssw.openedge.ls.proparse.z.a(SourceFile:401)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at eu.rssw.openedge.ls.proparse.z.initialize(SourceFile:158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:272)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[2024-09-06T13:59:33.134+0200] [INFO] Looking for ABL documentation cache in /home/user/.rssw/oedoc.bin
[2024-09-06T14:02:09.140+0200] [INFO] Shutdown request received
Sep 06, 2024 2:02:09 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:272)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(Unknown Source)
	at java.base/java.util.concurrent.Executors.newFixedThreadPool(Unknown Source)
	at eu.rssw.openedge.ls.proparse.z.shutdown(SourceFile:190)
	... 16 more

```

**Comment by gquerret** [comment]
Message has to be much more explicit in this case. The stack trace gives information (at least for me), but that's not what a user would expect.
