### ISSUE TITLE
ConcurrentModificationException while generating class documentation

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#193]
Only seen once (should inspect the log file to be sure it only happened once) during full compile of project (numThreads: 4)

```
[2024-09-09T15:05:49.781+0200] [ERROR] [<project name>] Error during class documentation phase
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at eu.rssw.openedge.ls.builder.x.run(SourceFile:157)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at eu.rssw.openedge.ls.proparse.x.a(SourceFile:290)
	at eu.rssw.openedge.ls.proparse.x.a(SourceFile:292)
	at eu.rssw.openedge.ls.proparse.x.a(SourceFile:292)
	at eu.rssw.openedge.ls.proparse.x.a(SourceFile:292)
	at eu.rssw.openedge.ls.proparse.x.a(SourceFile:292)
	at eu.rssw.openedge.ls.proparse.x.a(SourceFile:292)
	at eu.rssw.openedge.ls.proparse.x.a(SourceFile:75)
	at eu.rssw.openedge.ls.builder.q.a(SourceFile:910)
	at eu.rssw.openedge.ls.builder.z.a(SourceFile:40)
	at eu.rssw.openedge.ls.builder.z.apply(SourceFile:26)
	... 7 more
```

**Comment by gquerret** [comment]
What is the version number of the language server (ie first lines of the ABL Language Server output tab) ?

**Comment by LievenDeFoor** [comment]
Assuming this hasn't changed since yesterday:
`[2024-09-10T09:17:17.157+0200] [INFO] LanguageServerInfo: 1.16.0-SNAPSHOT-eb05ceb -- ClientInfo: Visual Studio Code 1.93.0 -- JVM: Eclipse Adoptium 17.0.12+7`

**Comment by gquerret** [comment]
Fixed in develop branch, will be included in next prerelease
