### ISSUE TITLE
ArrayIndexOutOfBoundsException: arraycopy: length -158 is negative

### ISSUE THREAD

**Issue by LievenDeFoor** [vscode-abl/vscode-abl#209]
```
[2024-09-10T12:27:16.989+0200] [INFO] [Glims] Compilation successful: be\mips\ablframework\gui\statusbar\IGlobalStatusBar.cls
[2024-09-10T12:27:17.013+0200] [ERROR] [Glims] Error during class documentation phase
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -158 is negative
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at eu.rssw.openedge.ls.builder.x.run(SourceFile:151)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -158 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.util.Arrays.copyOfRange(Unknown Source)
	at eu.rssw.pct.RCodeInfo.<init>(RCodeInfo.java:151)
	at eu.rssw.pct.RCodeInfo.<init>(RCodeInfo.java:105)
	at eu.rssw.pct.a.<init>(SourceFile:40)
	at eu.rssw.openedge.ls.builder.h.a(SourceFile:34)
	at eu.rssw.openedge.ls.builder.h.apply(SourceFile:24)
	... 7 more
[2024-09-10T12:27:17.014+0200] [INFO] [Glims] Compilation successful: be\mips\ablframework\gui\statusbar\IObjectStatusBar.cls
```
If you need more info to investigate let me know.

**Comment by gquerret** [comment]
Can you upload the rcode of `be\mips\ablframework\gui\statusbar\IGlobalStatusBar.cls` to[ https://upload.rssw.eu](https://upload.rssw.eu) ?

**Comment by LievenDeFoor** [comment]
I've recompiled and uploaded the file, but I'm not sure it's reproducible, as now I did not see any errors in the output log...

**Comment by gquerret** [comment]
I confirm the rcode is correct. I'll close the issue for now ; the LS probably tried to read the rcode while it was written by the AVM.
