### ISSUE TITLE
Multiple RCodeInfo$InvalidRCodeException occurences when compiling full project

### ISSUE THREAD

**Issue by gquerret** [vscode-abl/vscode-abl#32]
On behalf of RITS

Multiple occurences of this exception are found in the LS output log. Confirmed that those issues are randomly thrown (rcode can be parsed later without any problem).

```
[2022-10-14T18:07:51.598+0200] [ERROR] Unable to parse rcode xxxx.r - Please open issue on GitHub - eu.rssw.pct.RCodeInfo$InvalidRCodeException
[2022-10-14T18:07:51.598+0200] [ERROR] Caused by: eu.rssw.pct.RCodeInfo$InvalidRCodeException: Not enough bytes to reach debug segment
    at eu.rssw.pct.RCodeInfo.<init>(RCodeInfo.java:125)
    at eu.rssw.pct.RCodeInfo.<init>(RCodeInfo.java:97)
    at eu.rssw.openedge.ls.a.l.a(SourceFile:750)
    at eu.rssw.openedge.ls.a.C.b(SourceFile:119)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by gquerret** [comment]
Fixed in 1.3.11
