### ISSUE TITLE
Lowercasing not working in 1.4.4

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#52]
The `ABL: Convert to lowercase` command does not do anything in v1.4.4.  

Select a program (cls or p) with some uppercase code. CTRL-P and select the convert to lowercase command. Nothing happens. This worked in 1.4.3.

The following error is seen in the ABL Language Server log.
````
Jan 12, 2023 2:31:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
````

**Comment by gquerret** [comment]
What does the first line of the language server output say ? It should be the version number.

**Comment by PeterJudgeZA** [comment]
````
[2023-01-12T16:39:58.561-0500] [INFO] LanguageServerInfo: 1.5.0-SNAPSHOT-391f7c0 -- ClientInfo: Visual Studio Code 1.74.3
[2023-01-12T16:39:58.561-0500] [DEBUG] Client Capabilities: WS Config true -- WS Folder true -- Diagnotics true -- Symbol Hierarchy true -- Document Highlight true
`````

**Comment by gquerret** [comment]
Thx, will check that tomorrow.

**Comment by gquerret** [comment]
Confirmed, all commands going to the language server seem to have a problem. I'm having a look.

**Comment by mikefechner** [comment]
And I thought breaking the lowercasing was a step towards a code beautifier ;-)

**Comment by gquerret** [comment]
Fixed, sorry for the regression.
Version 1.4.5 is currently being uploaded to the marketplace (and open-vsx.org).

**Comment by PeterJudgeZA** [comment]
Thanks for the fast turnaround. Looks to be working now.

I am seeing a different error now, on save of a file.
````
[2023-01-13T08:24:58.814-0500] [INFO] Command line arguments: 
[2023-01-13T08:24:59.728-0500] [INFO] LanguageServerInfo: 1.5.0-SNAPSHOT-a7a171e -- ClientInfo: Visual Studio Code 1.74.3
[2023-01-13T08:24:59.728-0500] [DEBUG] Client Capabilities: WS Config true -- WS Folder true -- Diagnotics true -- Symbol Hierarchy true -- Document Highlight true
[2023-01-13T08:24:59.736-0500] [DEBUG] Found CABL License
[2023-01-13T08:24:59.745-0500] [INFO] Register CABL License for 'Consultingwerk' - Valid until 2022-12-31T00:00:00

<snip>

[2023-01-13T08:26:33.086-0500] [DEBUG] Lint rules execution for Consultingwerk\Web2\WebHandler\FileUploadWebHandler.cls
[2023-01-13T08:26:33.107-0500] [ERROR] Rule exception: 
org.sonar.plugins.openedge.api.InvalidLicenseException: Invalid license - Signature OK - Expiration KO
	at org.sonar.plugins.openedge.AbstractCommercialRule.setContext(SourceFile:116)
	at eu.rssw.openedge.ls.a.k.a(SourceFile:61)
	at eu.rssw.openedge.ls.a.k.apply(SourceFile:37)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at eu.rssw.openedge.ls.a.u.run(SourceFile:141)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
````

**Comment by gquerret** [comment]
`org.sonar.plugins.openedge.api.InvalidLicenseException: Invalid license - Signature OK - Expiration KO`

Did you buy your license ? :-)

**Comment by PeterJudgeZA** [comment]
> Did you buy your license ? :-)

> [2023-01-13T08:24:59.745-0500] [INFO] Register CABL License for 'Consultingwerk' - Valid until 2022-12-31T00:00:00

Apparently my brain thinks that it's stil 2022. My bad, sorry.
