### ISSUE TITLE
Three errors when configuring cabl rules

### ISSUE THREAD

**Issue by kenherring-rkt** [vscode-abl/vscode-abl#54]
Each error appears one a at a time, and after I remove each rule from `.vscode/cabl.json` the next one appears.  Only after removing the three rules mentioned in the below call stacks are we able to scan effectively.

The first two errors appear when the language server starts.  The third appears when scanning any file.

Json files (with .txt extension to make GitHub happy to accept the upload):
* [cabl-with-errors.json.txt](https://github.com/vscode-abl/vscode-abl/files/10435605/cabl-with-errors.json.txt)
* [cabl-without-errors.json.txt](https://github.com/vscode-abl/vscode-abl/files/10435606/cabl-without-errors.json.txt)

These rules aren't super important to us or anything, but figured you'd want to the bug report for possible mitigation next time you're working with this code.

```bash
[2023-01-17T08:31:43.373-0500] [ERROR] Unable to parse cabl.json...
java.lang.ClassNotFoundException: eu.rssw.cabl.security.DebuggerKeyword
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at eu.rssw.openedge.ls.a.m.h(SourceFile:558)
	at eu.rssw.openedge.ls.a.m.k(SourceFile:748)
	at eu.rssw.openedge.ls.a.m.e(SourceFile:668)
	at eu.rssw.openedge.ls.proparse.n.a(SourceFile:287)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:977)
	at eu.rssw.openedge.ls.proparse.n.a(SourceFile:285)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:212)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```bash
[2023-01-17T08:36:51.044-0500] [ERROR] Unable to parse cabl.json...
java.lang.ClassNotFoundException: eu.rssw.cabl.security.PropathAssignment
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at eu.rssw.openedge.ls.a.m.h(SourceFile:558)
	at eu.rssw.openedge.ls.a.m.k(SourceFile:748)
	at eu.rssw.openedge.ls.a.m.e(SourceFile:668)
	at eu.rssw.openedge.ls.proparse.n.a(SourceFile:287)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:977)
	at eu.rssw.openedge.ls.proparse.n.a(SourceFile:285)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:212)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```bash
[2023-01-17T08:39:11.994-0500] [ERROR] Rule exception: 
java.lang.UnsupportedOperationException
	at eu.rssw.openedge.ls.b.d.contents(SourceFile:96)
	at eu.rssw.antlr.proparse.checks.TabsIndent.execute(SourceFile:1024)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:57)
	at eu.rssw.openedge.ls.a.k.a(SourceFile:67)
	at eu.rssw.openedge.ls.a.k.apply(SourceFile:37)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at eu.rssw.openedge.ls.a.u.run(SourceFile:141)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by gquerret** [comment]
The current situation with VSCode / SonarLint is temporary. The rules are currently embedded in the language server (except security rules), and you have to declare the quality profile in cabl.json. As security rules are not included, you're getting this ClassNotFoundException.

What will come in future versions is the ability to bind a VSCode project to a SonarQube project (exactly as in Eclipse, or in VSCode with Java, Javascript, TS, ...). The LS will then be able to execute the rules that are configured in the project, no need to configure cabl.json anymore. Though it will still be possible to use cabl.json for unbound projects (i.e. in standalone mode).

**Comment by kenherring-rkt** [comment]
Sounds cool, look forward to seeing it.  Thanks for the info!
