### ISSUE TITLE
Proparse Error: No viable alternative at input '<tablename>'

### ISSUE THREAD

**Issue by xGerTowelie** [vscode-abl/vscode-abl#64]
I currently started using vscode instead of the pds for developing progress. The configuration in the 'openedge-project.json' is most likely finished. Compile errors on save works, but whenever I initially start the project in vscode my language server tells me this error message:

[2023-03-24T11:56:24.526+0100] [ERROR] Proparse error...
org.antlr.v4.runtime.misc.ParseCancellationException: No viable alternative at input 'DRC_Instance'
	at org.prorefactor.proparse.ProparseErrorStrategy.recover(ProparseErrorStrategy.java:97)
	at org.prorefactor.proparse.antlr4.Proparse.recordSearch(Proparse.java:42645)
	at org.prorefactor.proparse.antlr4.Proparse.canFindFunction(Proparse.java:28361)
	at org.prorefactor.proparse.antlr4.Proparse.builtinFunction(Proparse.java:5259)
	at org.prorefactor.proparse.antlr4.Proparse.expressionTerm2(Proparse.java:12147)
	at org.prorefactor.proparse.antlr4.Proparse.expressionTerm(Proparse.java:11620)
	at org.prorefactor.proparse.antlr4.Proparse.expression(Proparse.java:11248)
	at org.prorefactor.proparse.antlr4.Proparse.returnOption(Proparse.java:60232)
	at org.prorefactor.proparse.antlr4.Proparse.returnStatement(Proparse.java:60159)
	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3956)
	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1594)
	at org.prorefactor.proparse.antlr4.Proparse.codeBlock(Proparse.java:1495)
	at org.prorefactor.proparse.antlr4.Proparse.methodStatement(Proparse.java:53555)
	at org.prorefactor.proparse.antlr4.Proparse.inclassStatement(Proparse.java:4458)
	at org.prorefactor.proparse.antlr4.Proparse.classBlockOrStatement(Proparse.java:1735)
	at org.prorefactor.proparse.antlr4.Proparse.classCodeBlock(Proparse.java:1659)
	at org.prorefactor.proparse.antlr4.Proparse.classStatement(Proparse.java:19799)
	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3179)
	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1594)
	at org.prorefactor.proparse.antlr4.Proparse.program(Proparse.java:1430)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:342)
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:387)
	at eu.rssw.openedge.ls.a.w.a(SourceFile:32)
	at eu.rssw.openedge.ls.a.w.apply(SourceFile:19)
	at eu.rssw.openedge.ls.a.m.a(SourceFile:973)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2031)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:524)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:396)
	at org.prorefactor.proparse.antlr4.Proparse.recordSearch(Proparse.java:42630)
	... 29 more
	
	
I get this error several times for several tables. But I don't know what file is causing this and why?
Does anyone had that error already? And is there a way to dig further into the java error provided in the console?

Kind regards
Marcel

**Comment by gquerret** [comment]
Assuming `DRC_Instance` is a table of your schema, make sure the `dbConnections` section is configured correctly (see https://github.com/vscode-abl/vscode-abl#project-configuration). The dumpFile attribute is used by Proparse to parse your source code, so make it points to the right DF file.

**Comment by xGerTowelie** [comment]
Thanks for the hint! I accidentally forgot the .df as file ending on the dump file. The error has gone. But vscode still doesn't provide code completion for my tables. (also for variables, tt, ds, etc.) But already saw on the README, that it's still code work in progress. So I assume it's not working right now?

**Comment by gquerret** [comment]
There's a regression in current version (see #61). Next version will be there in the coming days. Still not perfect, but you should have some code completion.
