### ISSUE TITLE
Suppress Exception in log when r-code not present

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#76]
I opened a VS code workspace where previously I have deleted all r-code. The "ABL Language Server" console is full of these messages, probably 1 for each of the 5000 files in the project:

```
[2023-05-02T11:30:17.627+0200] [ERROR] Unable to parse rcode c:\work\SCL\Consultingwerk\OERA\RestResource\ISupportsRestMethods.r - Please open issue on GitHub - java.nio.file.NoSuchFileException
[2023-05-02T11:30:17.627+0200] [ERROR] Caused by: 
java.nio.file.NoSuchFileException: c:\work\SCL\Consultingwerk\OERA\RestResource\ISupportsRestMethods.r
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at eu.rssw.openedge.ls.a.m.a(SourceFile:869)
	at eu.rssw.openedge.ls.a.m.e(SourceFile:975)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

IMHO an informational message would be enough. No need for the Java stack-trace, no need to suggest logging a Github issue (well, I did that now).

**Comment by gquerret** [comment]
The files were probably deleted after the rcode directory scan was executed, so all rcode were already added to the stack, and several files were deleted when being processed by the executors.
Removing the stack trace in this specific case, message will be enough to find the root cause.
