### ISSUE TITLE
Add program name to Proparse error for better debugging

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#81]
I see a variety of errors in the language server logs, similar to the below. It would be nice to know which program caused these, so as to better log bugs.
I'm building 5500+ programs using 6 threads and so inferring a file name from the log may not be possible.

```
[2023-06-19T10:50:46.380-0400] [ERROR] Proparse error...
org.antlr.v4.runtime.misc.ParseCancellationException: Mismatched input ''SET'', expecting '{PERIOD, GET}'
	at org.prorefactor.proparse.ProparseErrorStrategy.recover(ProparseErrorStrategy.java:97)
	at org.prorefactor.proparse.antlr4.Proparse.definePropertyAccessorGetBlock(Proparse.java:35781)
	at org.prorefactor.proparse.antlr4.Proparse.definePropertyAccessor(Proparse.java:35649)
	at org.prorefactor.proparse.antlr4.Proparse.definePropertyStatement(Proparse.java:35412)
	at org.prorefactor.proparse.antlr4.Proparse.inClassStatement(Proparse.java:4676)
	at org.prorefactor.proparse.antlr4.Proparse.classBlockOrStatement(Proparse.java:1873)
	at org.prorefactor.proparse.antlr4.Proparse.classCodeBlock(Proparse.java:1729)
	at org.prorefactor.proparse.antlr4.Proparse.classStatement(Proparse.java:20704)
	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3479)
	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1604)
	at org.prorefactor.proparse.antlr4.Proparse.program(Proparse.java:1440)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:345)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:299)
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:390)
	at eu.rssw.openedge.ls.builder.w.a(SourceFile:32)
	at eu.rssw.openedge.ls.builder.w.apply(SourceFile:19)
	at eu.rssw.openedge.ls.builder.n.a(SourceFile:1035)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:270)
	at org.prorefactor.proparse.antlr4.Proparse.definePropertyAccessorGetBlock(Proparse.java:35762)
	... 21 more
```

````
[2023-06-19T10:50:45.437-0400] [ERROR] Proparse error...
org.antlr.v4.runtime.misc.ParseCancellationException: Mismatched input ''ToString'', expecting 'LEFTPAREN'
	at org.prorefactor.proparse.ProparseErrorStrategy.recover(ProparseErrorStrategy.java:97)
	at org.prorefactor.proparse.antlr4.Proparse.functionParams(Proparse.java:46616)
	at org.prorefactor.proparse.antlr4.Proparse.methodDefinitionStatement(Proparse.java:54945)
	at org.prorefactor.proparse.antlr4.Proparse.inInterfaceStatement(Proparse.java:5199)
	at org.prorefactor.proparse.antlr4.Proparse.interfaceBlockOrStatement(Proparse.java:2030)
	at org.prorefactor.proparse.antlr4.Proparse.interfaceCodeBlock(Proparse.java:1790)
	at org.prorefactor.proparse.antlr4.Proparse.interfaceStatement(Proparse.java:52601)
	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:4039)
	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1604)
	at org.prorefactor.proparse.antlr4.Proparse.program(Proparse.java:1440)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:345)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:299)
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:390)
	at eu.rssw.openedge.ls.builder.w.a(SourceFile:32)
	at eu.rssw.openedge.ls.builder.w.apply(SourceFile:19)
	at eu.rssw.openedge.ls.builder.n.a(SourceFile:1035)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:483)
	at org.antlr.v4.runtime.Parser.match(Parser.java:208)
	at org.prorefactor.proparse.antlr4.Proparse.functionParams(Proparse.java:46582)
	... 20 more
````

**Comment by gquerret** [comment]
Fixed
