### ISSUE TITLE
ABL: Convert to lowercase does not work if program does not compile

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#84]
If a (say) class does not compile, then the ABL: Convert to lowercase command does nothing. Same behaviour for convert to uppercase. Once the program compiles, the code is converted.

The language server logs this message which is totally expected.
```
[2023-07-20T12:07:37.470-0400] [ERROR] Syntax error -- unnamed.p:34:20 -- Unknown table: eCustomer
[2023-07-20T12:07:37.470-0400] [ERROR] Proparse error...
org.antlr.v4.runtime.misc.ParseCancellationException: Syntax error
	at org.prorefactor.proparse.ProparseErrorStrategy.recover(ProparseErrorStrategy.java:97)
	at org.prorefactor.proparse.antlr4.Proparse.record(Proparse.java:14057)
	at org.prorefactor.proparse.antlr4.Proparse.recordPhrase(Proparse.java:60609)
	at org.prorefactor.proparse.antlr4.Proparse.recordSearch(Proparse.java:43801)
	at org.prorefactor.proparse.antlr4.Proparse.findStatement(Proparse.java:43453)
	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3955)
	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1604)
	at org.prorefactor.proparse.antlr4.Proparse.codeBlock(Proparse.java:1505)
	at org.prorefactor.proparse.antlr4.Proparse.methodStatement(Proparse.java:54650)
	at org.prorefactor.proparse.antlr4.Proparse.inClassStatement(Proparse.java:4760)
	at org.prorefactor.proparse.antlr4.Proparse.classBlockOrStatement(Proparse.java:1873)
	at org.prorefactor.proparse.antlr4.Proparse.classCodeBlock(Proparse.java:1729)
	at org.prorefactor.proparse.antlr4.Proparse.classStatement(Proparse.java:20704)
	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3479)
	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1604)
	at org.prorefactor.proparse.antlr4.Proparse.program(Proparse.java:1440)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:345)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:299)
	at eu.rssw.openedge.ls.builder.n.a(SourceFile:1126)
	at eu.rssw.openedge.ls.proparse.r.a(SourceFile:15114)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.antlr.v4.runtime.FailedPredicateException: failed predicate: { recordSemanticPredicate() }?
	at org.prorefactor.proparse.antlr4.Proparse.record(Proparse.java:14048)
	... 25 more
```

**Comment by mikefechner** [comment]
Not surprising - as Proparse has similar requirements as the Compiler. Fix your compile error ;)

**Comment by PeterJudgeZA** [comment]
Things like colour-coding continue to work in VS Code (and PDSOE for that matter), even when code does not compile.

**Comment by gquerret** [comment]
That won't be fixed ; as Mike said, the conversion relies on the parser (in order to be accurate).
