### ISSUE TITLE
Java ConcurrentModificationException exception thrown during build

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#90]
I see the below error frequently in the ABL Language server logs during a build (eg restart after deleting all r-code). 

I have 4 projects with 6, 2, 1 and 1 threads configured.

Extension 1.4.13 with `[2023-08-04T14:57:49.157-0400] [INFO] LanguageServerInfo: 1.7.0-SNAPSHOT-18361f5 -- ClientInfo: Visual Studio Code 1.81.0` 

```
[2023-08-04T15:00:29.685-0400] [ERROR] Error during class documentation phase
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at eu.rssw.openedge.ls.builder.v.run(SourceFile:149)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1855)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at eu.rssw.openedge.ls.builder.s.getAllClassesFromPackage(SourceFile:1717)
	at org.prorefactor.proparse.support.ClassFinder.addPath(ClassFinder.java:44)
	at org.prorefactor.proparse.support.ParserSupport.usingState(ParserSupport.java:182)
	at org.prorefactor.proparse.antlr4.Proparse.usingStatement(Proparse.java:2662)
	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:4459)
	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1604)
	at org.prorefactor.proparse.antlr4.Proparse.program(Proparse.java:1440)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:329)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:299)
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:390)
	at eu.rssw.openedge.ls.builder.w.a(SourceFile:36)
	at eu.rssw.openedge.ls.builder.w.apply(SourceFile:23)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	... 6 more
```

**Comment by gquerret** [comment]
Will be fixed

**Comment by gquerret** [comment]
Fixed
